### ISSUE TITLE
Sophus has problems running Revo  

### ISSUE THREAD

**Issue by RuiYangQuan** [fabianschenk/REVO#7]
This error occurs when I run REVO on my own data set：

Sophus ensure failed in function 'static Sophus::SO3<Scalar_> Sophus::SO3<Scalar_, Options>::expAndTheta(const Tangent&, Sophus::SO3<Scalar_, Options>::Scalar*) [with Scalar_ = float; int Options = 0; Sophus::SO3<Scalar_, Options>::Tangent = Eigen::Matrix<float, 3, 1>; Sophus::SO3<Scalar_, Options>::Scalar = float]', file '/home/one/REVO-fabian/thirdparty/Sophus/sophus/so3.hpp', line 563.
SO3::exp failed! omega: -nan -nan    0, real: -nan, img: -nan
Aborted (core dumped)

In this regard, I have made some attempts, such as changing camera internal parameters, Canny threshold value and resolution, but none of them had any effect. Could you please give me some suggestions

**Comment by fabianschenk** [comment]
Hi @RuiYangQuan ,

This error probably happens when REVO can't estimate a valid pose. Apparently, I forgot to catch this somewhere in the code base. You could just go to the part in the code where this happens and try to check before converting the rotation matrix to its minimal representation.

Good luck :D

**Comment by RuiYangQuan** [comment]
Thank you for your reply. I will try something
@fabianschenk
